#!/bin/bash -xe
# This script is run when a host-up-response is received by a newbie

# Variables:
# $@ - Decoded Payload

export NETNAME=${NETNAME:-$(tail -1 /etc/tinc/nets.boot)}
PIDFILE=/usr/var/run/tinc.${NETNAME}.pid
TINC=${TINC:-tinc --pidfile=${PIDFILE}}

# Import the payload generated by a tinc-up on a host
echo "$@" | ${TINC} import || true

${TINC} del ConnectTo ${NODE} || true
${TINC} add ConnectTo ${NODE}

${TINC} reload

# Tell tinc to try connecting to everything
kill -ALRM $(cat ${PIDFILE})

exit 0
