#!/bin/bash -xe
# This event fires when a newbie broadcasts they are up

# Variables:
# $@ - Decoded Payload

export NETNAME=${NETNAME:-$(tail -1 /etc/tinc/nets.boot)}
PIDFILE=/usr/var/run/tinc.${NETNAME}.pid
TINC=${TINC:-tinc --pidfile=${PIDFILE}}

# Import the payload generated by a tinc-up on a host
echo "$@" | ${TINC} import || true

${TINC} del ConnectTo ${NODE} || true
${TINC} add ConnectTo ${NODE}

${TINC} reload

# Tell tinc to try connecting to everything
kill -ALRM $(cat ${PIDFILE})

# This is an existing node, tell the newbie about everything we know
consul event -name tinc/v1.1/host-up-response "$(${TINC} export-all)"

exit 0
