version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

networks:
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local
  mysql-data:
    driver: local
  pandorafms-data:
    driver: local

services:
  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    volumes:
      - traefik-ssl:/ssl
    restart: always
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "8080"
      HTTPS_PORT: "8443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      SUBDOMAINS: ${SUBDOMAINS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  pandora-mysql:
    image: pandorafms/pandorafms-mysql:6
    container_name: pandora-mysql
    hostname: pandora-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PANDORA_DB_NAME}
      MYSQL_USER: ${PANDORA_DB_USER}
      MYSQL_PASSWORD: ${PANDORA_DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    restart: always
    healthcheck:
      test: mysqladmin -h localhost -u $${MYSQL_USER} -p$${MYSQL_PASSWORD} ping
      timeout: 20s
      retries: 10
    logging: *default-logging
    labels:
      - "traefik.enable=false"

  pandora-server:
    build: docker-pandorafms/pandorafms-server/
    image: pandorafms/pandorafms-server:6
    container_name: pandora-server
    hostname: pandora-server
    volumes:
      - traefik-ssl:/ssl
    environment:
      PANDORA_DB_HOST: ${PANDORA_DB_HOST}
      PANDORA_DB_NAME: ${PANDORA_DB_NAME}
      PANDORA_DB_USER: ${PANDORA_DB_USER}
      PANDORA_DB_PASSWORD: ${PANDORA_DB_PASSWORD}
    ports:
      - 41121:41121
    depends_on:
      pandora-mysql:
        condition: service_healthy
    networks:
      - default
    restart: always
    logging: *default-logging
    labels:
      - "traefik.enable=false"

  pandora-console:
    build: docker-pandorafms/pandorafms-console/
    image: pandorafms/pandorafms-console:6
    container_name: pandora-console
    hostname: console.${DNS_DOMAIN}
    volumes:
      - traefik-ssl:/ssl
    ports:
#    - 80:80
    - 60080:80
    environment:
      PANDORA_DB_HOST: ${PANDORA_DB_HOST}
      PANDORA_DB_NAME: ${PANDORA_DB_NAME}
      PANDORA_DB_USER: ${PANDORA_DB_USER}
      PANDORA_DB_PASSWORD: ${PANDORA_DB_PASSWORD}
      SERVER_SSH_ADDR: anyterm-ssh.${DNS_DOMAIN}
      SERVER_SSH_PORT: 443
      SERVER_TELNET_ADDR: anyterm-telnet.${DNS_DOMAIN}
      SERVER_TELNET_PORT: 443
      HOMEURL: /pandora_console
      PUBLIC_URL: https://console.${DNS_DOMAIN}:8443/pandora_console/
      HTTPS: 'true'
    depends_on:
      pandora-mysql:
        condition: service_healthy
    networks:
      - default
    restart: always
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=console"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:console.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  pandora-anyterm-ssh:
    build: docker-pandorafms/pandorafms-anyterm/
    image: sofwerx/pandorafms-anyterm
    container_name: pandora-anyterm-ssh
    hostname: pandora-anyterm-ssh
    ports:
      - 127.0.0.1:8022:8022
    environment:
      PORT: 8022
    networks:
      - default
    restart: always
    command: anytermd -f -p 8022 -u pandora -c ssh
    labels:
      - "traefik.enable=true"
      - "traefik.backend=anyterm-ssh"
      - "traefik.port=8022"
      - "traefik.frontend.rule=Host:anyterm-ssh.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  pandora-anyterm-telnet:
    build: docker-pandorafms/pandorafms-anyterm/
    image: sofwerx/pandorafms-anyterm
    container_name: pandora-anyterm-telnet
    hostname: pandora-anyterm-telnet
    ports:
      - 127.0.0.1:8023:8023
    environment:
      PORT: 8023
    networks:
      - default
    restart: always
    command: anytermd -f -p 8023 -u pandora -c telnet
    labels:
      - "traefik.enable=true"
      - "traefik.backend=anyterm-telnet"
      - "traefik.port=8023"
      - "traefik.frontend.rule=Host:anyterm-telnet.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

